services:
  db:
    image: mysql:8.0
    container_name: db
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 20s
      timeout: 10s
      retries: 5
    environment:
      MYSQL_ROOT_PASSWORD: CABApp#mysql!
      MYSQL_DATABASE: cab_app
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      VITE_APP_API_URL: http://backend:8080
      GOOGLE_API_KEY: 
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_CONNECTION_STRING: mysql://root:CABApp%23mysql%21@db:3306/cab_app
      GOOGLE_API_KEY:
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

volumes:
  mysql-data:
    driver: local

networks:
  app-network: 