services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: CABApp#mysql!
      MYSQL_DATABASE: cab_app
      MYSQL_USER: prod
      MYSQL_PASSWORD: pr0d#Docker
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network
			
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - VITE_APP_API_URL=http://backend:8080
      - VITE_GOOGLE_API_KEY=
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_CONNECTION_STRING="mysql://prod:pr0d#Docker@mysql:3306/cab_app"
      - GOOGLE_API_KEY=
    depends_on:
      - mysql
    networks:
      - app-network

volumes:
  mysql-data:
    driver: local

networks:
  app-network: 